Betaling form and api
Justwouter/WDPR-SE2 pull request #46
Opened 2023-01-13 07:13 UTC by nhorvin

TEST

Response van de POST request op api/Betaling: 
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-7c1f880ea31e0e996f9a9bb22b11e9d1-7be35cec08cded0d-00","errors":{"reference":["The value '1673593910529' is not valid for reference."]}}

2023-01-16 09:37 UTC, Studeeric requested changes
1 dingetje anders, gewoon een console log die ik gevonden had.

2023-01-16 09:37 UTC, Studeeric commented on frontend/src/components/ProgrammaForm.js
> +      console.log(zaal)
Console log moet er uit.

2023-01-16 09:51 UTC, Justwouter commented on frontend/src/components/Bestellen/BetalingsForm.js
> +  'url': 'http://api.localhost/api/Betaling'
Returning to an api page? not very cash money of you

2023-01-17 23:03 UTC, Justwouter approved these changes
Looks Good To Me
Als de docenten hun API/Site fixen zou dit moeten werken lijkt me.

2023-01-17 23:06 UTC, Justwouter commented on frontend/src/components/ProgrammaForm.js
> +      console.log(zaal)
Removed it 0)

2023-01-17 23:07 UTC, Justwouter commented
Not waiting for Eric to review a single console.log(). Sorry @Studeeric

2023-01-17 23:07 UTC, merged